[package]
name          = "alternador_wallpapers"
version       = "1.0.0"
edition       = "2021"
rust-version  = "1.60"

[dependencies]
date_time   = "2.2.0"
serde_json  = "1.0.91"

[target.'cfg(debug_assertions)'.dependencies]
utilitarios = { path="../rust-utilitarios/" }


